package env

const (
	HelpContent = "KioqIEZvbGRlcmNvZGUgQ0xJICoqKgoKKiBUaGlzIGlzIGNsaSB0b29sIHdoaWNoIGhlbHBzIHlvdSB0byB1c2luZyBmb2xkZXJjb2RlLmNvbSB2aWEgY2xpLgoqIFlvdSBjYW4gdHJhbnNmZXIgeW91ciBmaWxlcyBlYXNpbHkuCgpIb3cgdG8gdXNlPwoKKiogVXBsb2FkIEZpbGVzICoqCiQgZmNvZGUgdXBsb2FkIHgudHh0IHkudHh0IHoub3V0CiMgVGhpcyBjb21tYW5kIHJldHVybiBhIGNvZGUgbGlrZSAnYWQ0NycKCioqIEdldCBGaWxlcyAqKgokIGZjb2RlIGdldCB7Y29kZX0KJCBmY29kZSBnZXQgYWQ0NwojIFRoaXMgY29tbWFuZCBkb3dubG9hZHMgdGhlIGZpbGVzIHVwbG9hZGVkIHRvIGFkNDc="
	ApiUrlBase  = "https://api.foldercode.com"
)
