package env

const (
	HelpContent = "KioqIEZvbGRlcmNvZGUgQ0xJICoqKgoKKiBUaGlzIGlzIGNsaSB0b29sIHdoaWNoIGhlbHBzIHlvdSB0byB1c2luZyBmb2xkZXJjb2RlLmNvbSB2aWEgY2xpLgoqIFlvdSBjYW4gdHJhbnNmZXIgeW91ciBmaWxlcyBlYXNpbHkuCgpIb3cgdG8gdXNlPwoKKiogVXBsb2FkIEZpbGVzICoqCiQgZmMgdXBsb2FkIHgudHh0IHkudHh0IHoub3V0CiMgVGhpcyBjb21tYW5kIHJldHVybiBhIGNvZGUgbGlrZSAnYWQ0NycKCioqIEdldCBGaWxlcyAqKgokIGZjIGdldCB7Y29kZX0KJCBmYyBnZXQgYWQ0NwojIFRoaXMgY29tbWFuZCBkb3dubG9hZHMgdGhlIGZpbGVzIHVwbG9hZGVkIHRvIGFkNDc="
	ApiUrlBase  = "https://api.foldercode.com"
)
